### ISSUE TITLE
Album art?

### ISSUE THREAD

**Issue by developerfromjokela** [rohilpatel1/applemusicrpc#7]
Would it be possible to show album art?

**Comment by rohilpatel1** [comment]
Unfortunately discord doesn't allow you to do that; they make you upload all the images you use to the portal and then do it. If they allowed it by a link, then I would do it.

**Comment by developerfromjokela** [comment]
[https://www.reddit.com/r/discordapp/comments/rndazc/discord_finally_enabled_the_ability_to_load_rich/](https://www.reddit.com/r/discordapp/comments/rndazc/discord_finally_enabled_the_ability_to_load_rich/)

have a look at this
